// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../src/js/app.js', ['logdx.sch.App'], ['goog.dom', 'goog.dom.ViewportSizeMonitor', 'goog.events', 'goog.events.EventType', 'goog.math', 'goog.style', 'goog.ui.Button', 'goog.ui.Dialog', 'goog.ui.SplitPane', 'logdx.sch.Canvas', 'logdx.sch.Canvas.EventType', 'logdx.sch.Figure', 'logdx.sch.Oval', 'logdx.sch.paper', 'logdx.sch.sheet.orientation', 'logdx.sch.sheet.size', 'logdx.sch.toolbar', 'logdx.sch.toolpan', 'logdx.sch.toolselect'], false);
goog.addDependency('../../../src/js/canvas.js', ['logdx.sch.Canvas', 'logdx.sch.Canvas.EventType'], ['goog.dom', 'goog.dom.classes', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.events.KeyCodes', 'goog.events.KeyHandler', 'goog.events.KeyHandler.EventType', 'goog.events.MouseWheelHandler', 'goog.math', 'goog.style', 'goog.ui.Component', 'logdx.sch.Figure', 'logdx.sch.tool', 'logdx.sch.tool.MouseEvent', 'logdx.svg.Canvas'], false);
goog.addDependency('../../../src/js/command.js', ['logdx.sch.Command'], ['goog.Disposable', 'goog.math'], false);
goog.addDependency('../../../src/js/figure.js', ['logdx.sch.Action', 'logdx.sch.Figure'], ['goog.Disposable', 'goog.math', 'logdx.sch.Handle'], false);
goog.addDependency('../../../src/js/handle.js', ['logdx.sch.Handle'], ['goog.math'], false);
goog.addDependency('../../../src/js/init.js', ['logdx.sch.init'], ['goog.dom', 'logdx.sch.App'], false);
goog.addDependency('../../../src/js/paper.js', ['logdx.sch.paper', 'logdx.sch.sheet.orientation', 'logdx.sch.sheet.size'], [], false);
goog.addDependency('../../../src/js/shape/oval.js', ['logdx.sch.Oval'], ['goog.math', 'logdx.sch.Figure'], false);
goog.addDependency('../../../src/js/svg/element.js', ['logdx.svg.Element'], ['goog.events', 'goog.events.EventTarget', 'goog.math.Coordinate'], false);
goog.addDependency('../../../src/js/svg/ellipseelement.js', ['logdx.svg.EllipseElement'], ['logdx.svg.Element'], false);
goog.addDependency('../../../src/js/svg/groupelement.js', ['logdx.svg.GroupElement'], ['logdx.svg.Element'], false);
goog.addDependency('../../../src/js/svg/rectelement.js', ['logdx.svg.RectElement'], ['logdx.svg.Element'], false);
goog.addDependency('../../../src/js/svg/svg.js', ['logdx.svg.Canvas'], ['goog.dom', 'goog.math', 'goog.ui.Component', 'logdx.svg.EllipseElement', 'logdx.svg.GroupElement', 'logdx.svg.RectElement'], false);
goog.addDependency('../../../src/js/tool.js', ['logdx.sch.tool', 'logdx.sch.tool.MouseEvent'], ['goog.math'], false);
goog.addDependency('../../../src/js/toolbar.js', ['logdx.sch.toolbar', 'logdx.sch.toolbar.tools'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'goog.math', 'goog.style', 'goog.ui.Button', 'goog.ui.Component.EventType', 'goog.ui.Component.State', 'goog.ui.Menu', 'goog.ui.MenuItem', 'goog.ui.SelectionModel', 'goog.ui.Separator', 'goog.ui.Toolbar', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarMenuButton', 'goog.ui.ToolbarRenderer', 'goog.ui.ToolbarSelect', 'goog.ui.ToolbarSeparator', 'goog.ui.ToolbarToggleButton', 'logdx.sch.toolpan', 'logdx.sch.toolselect', 'logdx.sch.tooltip'], false);
goog.addDependency('../../../src/js/toolpan.js', ['logdx.sch.toolpan'], ['logdx.sch.tool'], false);
goog.addDependency('../../../src/js/toolselect.js', ['logdx.sch.toolselect'], ['goog.math', 'logdx.sch.Action', 'logdx.sch.tool'], false);
goog.addDependency('../../../src/js/tooltip.js', ['logdx.sch.tooltip'], ['goog.Timer', 'goog.dom', 'goog.dom.classes', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventType', 'goog.positioning.AnchoredPosition', 'goog.style', 'goog.ui.Component'], false);
goog.addDependency('../../../src/js/transform.js', ['logdx.Transform'], ['goog.math.Vec2'], false);
