// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../src/js/app.js', ['logdx.sch.app'], ['goog.dom', 'goog.dom.ViewportSizeMonitor', 'goog.events', 'goog.events.EventType', 'goog.style', 'goog.ui.Button', 'goog.ui.Dialog', 'goog.ui.SplitPane', 'logdx.sch.canvas', 'logdx.sch.canvas.EventType', 'logdx.sch.figure', 'logdx.sch.paper', 'logdx.sch.sheet.orientation', 'logdx.sch.sheet.size', 'logdx.sch.toolbar', 'logdx.sch.toolpan', 'logdx.sch.toolselect']);
goog.addDependency('../../../src/js/canvas.js', ['logdx.sch.canvas', 'logdx.sch.canvas.EventType'], ['goog.dom', 'goog.dom.classes', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.events.KeyCodes', 'goog.events.KeyHandler', 'goog.events.KeyHandler.EventType', 'goog.events.MouseWheelHandler', 'goog.math', 'goog.style', 'goog.ui.Component', 'logdx.sch.figure', 'logdx.sch.tool', 'logdx.sch.tool.MouseEvent', 'logdx.svg.Canvas']);
goog.addDependency('../../../src/js/figure.js', ['logdx.sch.figure'], ['goog.math', 'goog.ui.Component']);
goog.addDependency('../../../src/js/init.js', ['logdx.sch.init'], ['goog.dom', 'logdx.sch.app']);
goog.addDependency('../../../src/js/paper.js', ['logdx.sch.paper', 'logdx.sch.sheet.orientation', 'logdx.sch.sheet.size'], []);
goog.addDependency('../../../src/js/svg/element.js', ['logdx.svg.Element'], ['goog.events', 'goog.events.EventTarget', 'goog.math.Coordinate']);
goog.addDependency('../../../src/js/svg/ellipseelement.js', ['logdx.svg.EllipseElement'], ['logdx.svg.Element']);
goog.addDependency('../../../src/js/svg/groupelement.js', ['logdx.svg.GroupElement'], ['logdx.svg.Element']);
goog.addDependency('../../../src/js/svg/rectelement.js', ['logdx.svg.RectElement'], ['logdx.svg.Element']);
goog.addDependency('../../../src/js/svg/svg.js', ['logdx.svg.Canvas'], ['goog.dom', 'goog.math', 'goog.ui.Component', 'logdx.svg.EllipseElement', 'logdx.svg.GroupElement', 'logdx.svg.RectElement']);
goog.addDependency('../../../src/js/tool.js', ['logdx.sch.tool', 'logdx.sch.tool.MouseEvent'], ['goog.math']);
goog.addDependency('../../../src/js/toolbar.js', ['logdx.sch.toolbar'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'goog.math', 'goog.style', 'goog.ui.Button', 'goog.ui.Component.EventType', 'goog.ui.Component.State', 'goog.ui.Menu', 'goog.ui.MenuItem', 'goog.ui.SelectionModel', 'goog.ui.Separator', 'goog.ui.Toolbar', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarMenuButton', 'goog.ui.ToolbarRenderer', 'goog.ui.ToolbarSelect', 'goog.ui.ToolbarSeparator', 'goog.ui.ToolbarToggleButton', 'logdx.sch.toolpan', 'logdx.sch.toolselect', 'logdx.sch.tooltip']);
goog.addDependency('../../../src/js/toolpan.js', ['logdx.sch.toolpan'], ['logdx.sch.tool']);
goog.addDependency('../../../src/js/toolselect.js', ['logdx.sch.toolselect'], ['goog.math', 'logdx.sch.tool']);
goog.addDependency('../../../src/js/tooltip.js', ['logdx.sch.tooltip'], ['goog.Timer', 'goog.dom', 'goog.dom.classes', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventType', 'goog.positioning.AnchoredPosition', 'goog.style', 'goog.ui.Component']);
